"""
Augmentation Study — Does Synthetic Data Improve KL Classification?
====================================================================
Trains two identical ResNet-18 classifiers and compares their performance
on the SAME held-out real test set:

  Baseline   : trained on real images only
  Augmented  : trained on real images + synthetic images generated by
               the CycleGAN or diffusion model for rare KL grades

The key question:
  Does adding synthetic KL=2 (translated from KL=1) and KL=3 (translated
  from KL=2) images to the training set meaningfully improve the model's
  ability to classify rare/severe grades on real test images?

Experimental design
-------------------
  • Patient-level train/val/test split (same seed as kl_classifier.py)
    → test set is ALWAYS real images only, never contaminated with fakes
  • Synthetic images are added ONLY to the training split
  • Same model architecture, hyper-parameters, and training procedure
    → the only variable is whether synthetic data is present
  • Metrics reported per-class (precision, recall, F1) to show improvement
    on rare grades specifically

Supported generator sources
----------------------------
  --generator cyclegan   : uses kl_transition_generator.py (G_final.pt)
  --generator diffusion  : uses diffusion_generator.py (unet_best.pt)

Run
---
    # First train the generators, then:
    python models/augmentation_study.py --generator cyclegan
    python models/augmentation_study.py --generator diffusion

Outputs  (models/augmentation_study/)
---------------------------------------
    baseline_confusion.png
    augmented_confusion.png
    comparison_report.png        — side-by-side per-class F1 bar chart
    comparison_roc.png           — overlaid ROC curves for both models
    augmentation_study_results.csv

Requirements
------------
    pip install torch torchvision pandas openpyxl pillow matplotlib tqdm scikit-learn
"""

import argparse
import re
import zipfile
from io import BytesIO
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
from PIL import Image
from sklearn.metrics import (
    ConfusionMatrixDisplay,
    classification_report,
    f1_score,
    roc_auc_score,
    roc_curve,
)
from sklearn.preprocessing import label_binarize
from torch.utils.data import DataLoader, Dataset, WeightedRandomSampler
from torchvision import models, transforms
from tqdm import tqdm

# ── Paths ─────────────────────────────────────────────────────────────────────
ROOT      = Path(__file__).parent.parent
XLSX_PATH = ROOT / "data" / "hand.xlsx"
ZIP_PATH  = ROOT / "data" / "Finger Joints.zip"
OUT_DIR   = Path(__file__).parent / "augmentation_study"

IMG_SIZE   = 224
KL_CLASSES = [0, 1, 2, 3, 4]
N_CLASSES  = len(KL_CLASSES)

JOINT_MAP = {
    "dip2": "DIP2", "dip3": "DIP3", "dip4": "DIP4", "dip5": "DIP5",
    "mcp2": "MCP2", "mcp3": "MCP3", "mcp4": "MCP4", "mcp5": "MCP5",
    "pip2": "PIP2", "pip3": "PIP3", "pip4": "PIP4", "pip5": "PIP5",
}

# Grades for which we generate synthetic data (rare in real dataset)
AUGMENT_GRADES = [2, 3]
# How many synthetic images to add per grade
N_SYNTHETIC_PER_GRADE = 500


# ── Real image dataset (mirrors kl_classifier.py) ────────────────────────────
def build_index(joint_filter=None):
    df = pd.read_excel(XLSX_PATH)
    df["img_id"] = df["id"].astype(str)
    img_to_kl: dict[str, int] = {}
    for img_joint, score_joint in JOINT_MAP.items():
        if joint_filter and img_joint != joint_filter:
            continue
        kl_col = f"v00{score_joint}_KL"
        if kl_col not in df.columns:
            continue
        for pid, kl in df.set_index("img_id")[kl_col].dropna().astype(int).items():
            img_to_kl[f"Finger Joints/{pid}_{img_joint}.png"] = kl

    pat = re.compile(r"Finger Joints/(\d+)_(\w+)\.png")
    index = []
    with zipfile.ZipFile(ZIP_PATH, "r") as z:
        for name in z.namelist():
            if not name.endswith(".png"):
                continue
            m = pat.match(name)
            if not m:
                continue
            if joint_filter and m.group(2) != joint_filter:
                continue
            kl = img_to_kl.get(name)
            if kl is None:
                continue
            index.append((name, kl))
    return index


def patient_split(index, val_frac=0.15, test_frac=0.15, seed=42):
    """Identical split logic to kl_classifier.py — same seed = same split."""
    pat = re.compile(r"Finger Joints/(\d+)_")
    pid_to_items: dict[str, list] = {}
    for item in index:
        pid = pat.match(item[0]).group(1)
        pid_to_items.setdefault(pid, []).append(item)

    rng  = np.random.default_rng(seed)
    pids = np.array(sorted(pid_to_items.keys()))
    rng.shuffle(pids)
    n         = len(pids)
    n_test    = int(n * test_frac)
    n_val     = int(n * val_frac)
    test_pids = set(pids[:n_test])
    val_pids  = set(pids[n_test: n_test + n_val])
    train_pids= set(pids[n_test + n_val:])

    def gather(pid_set):
        out = []
        for pid in pid_set:
            out.extend(pid_to_items[pid])
        return out

    return gather(train_pids), gather(val_pids), gather(test_pids)


class RealDataset(Dataset):
    def __init__(self, index, transform):
        self.index     = index
        self.transform = transform
        self._zip      = None

    def _get_zip(self):
        if self._zip is None:
            self._zip = zipfile.ZipFile(ZIP_PATH, "r")
        return self._zip

    def __len__(self):
        return len(self.index)

    def __getitem__(self, idx):
        path, kl = self.index[idx]
        with self._get_zip().open(path) as f:
            img = Image.open(BytesIO(f.read())).convert("L")
        return self.transform(img), kl


class SyntheticDataset(Dataset):
    """Wraps a list of pre-generated (tensor, label) pairs."""

    def __init__(self, images: list[tuple[torch.Tensor, int]], transform):
        self.images    = images
        self.transform = transform

    def __len__(self):
        return len(self.images)

    def __getitem__(self, idx):
        tensor, kl = self.images[idx]
        # tensor is already (1, H, W) in [-1,1] — resize to IMG_SIZE and normalise
        pil  = transforms.ToPILImage()(tensor * 0.5 + 0.5)
        return self.transform(pil), kl


from torch.utils.data import ConcatDataset


# ── Synthetic image generation ────────────────────────────────────────────────
def generate_cyclegan(source_kl: int, target_kl: int, n: int,
                      train_index: list, device: torch.device) -> list[tuple]:
    """
    Load a trained CycleGAN G_final.pt and translate real training images
    from source_kl to target_kl.  Returns list of (tensor, target_kl) pairs.
    """
    import sys
    sys.path.insert(0, str(Path(__file__).parent))
    from kl_transition_generator import ResNetGenerator

    ckpt_dir = Path(__file__).parent / f"kl{source_kl}_to_kl{target_kl}_cyclegan"
    if not (ckpt_dir / "G_final.pt").exists():
        print(f"  ⚠  CycleGAN checkpoint not found at {ckpt_dir}. "
              f"Run: python models/kl_transition_generator.py "
              f"--source_kl {source_kl} --target_kl {target_kl}")
        return []

    G = ResNetGenerator().to(device)
    G.load_state_dict(torch.load(ckpt_dir / "G_final.pt", map_location=device))
    G.eval()

    # Pull real source images from the training split
    source_paths = [p for p, kl in train_index if kl == source_kl]
    np.random.shuffle(source_paths)
    tf = transforms.Compose([
        transforms.Resize(64), transforms.CenterCrop(64),
        transforms.ToTensor(), transforms.Normalize([0.5], [0.5]),
    ])

    results = []
    with zipfile.ZipFile(ZIP_PATH, "r") as z:
        for path in source_paths[:n]:
            with z.open(path) as f:
                img = Image.open(BytesIO(f.read())).convert("L")
            tensor = tf(img).unsqueeze(0).to(device)
            with torch.no_grad():
                fake = G(tensor).squeeze(0).cpu()
            results.append((fake, target_kl))

    print(f"  Generated {len(results)} KL={target_kl} images via CycleGAN.")
    return results


def generate_diffusion(target_kl: int, n: int, device: torch.device) -> list[tuple]:
    """
    Load a trained diffusion model and generate n synthetic images for target_kl.
    Returns list of (tensor, target_kl) pairs.
    """
    import sys
    sys.path.insert(0, str(Path(__file__).parent))
    from diffusion_generator import UNet, NoiseSchedule, ddim_sample

    ckpt = Path(__file__).parent / "diffusion_kl" / "unet_best.pt"
    if not ckpt.exists():
        print(f"  ⚠  Diffusion checkpoint not found at {ckpt}. "
              f"Run: python models/diffusion_generator.py --mode train")
        return []

    schedule = NoiseSchedule(device=device)
    model    = UNet(n_classes=N_CLASSES).to(device)
    model.load_state_dict(torch.load(ckpt, map_location=device))

    results = []
    batch_size = 32
    generated  = 0
    while generated < n:
        bsz = min(batch_size, n - generated)
        cls = torch.full((bsz,), target_kl, dtype=torch.long, device=device)
        imgs = ddim_sample(model, schedule, cls, bsz, device, ddim_steps=50)
        for img in imgs:
            results.append((img.cpu(), target_kl))
        generated += bsz

    print(f"  Generated {len(results)} KL={target_kl} images via Diffusion.")
    return results


# ── Model ─────────────────────────────────────────────────────────────────────
def build_model():
    model = models.resnet18(weights=models.ResNet18_Weights.DEFAULT)
    old_conv = model.conv1
    new_conv = nn.Conv2d(1, old_conv.out_channels, kernel_size=old_conv.kernel_size,
                         stride=old_conv.stride, padding=old_conv.padding, bias=False)
    with torch.no_grad():
        new_conv.weight.copy_(old_conv.weight.mean(dim=1, keepdim=True))
    model.conv1 = new_conv
    model.fc    = nn.Sequential(nn.Dropout(0.4), nn.Linear(model.fc.in_features, N_CLASSES))
    return model


def train_model(train_ds, val_ds, device, epochs=20, lr=3e-4, label=""):
    # Weighted sampler
    def get_labels(ds):
        if hasattr(ds, "index"):
            return [kl for _, kl in ds.index]
        if hasattr(ds, "images"):
            return [kl for _, kl in ds.images]
        # ConcatDataset
        out = []
        for sub in ds.datasets:
            out.extend(get_labels(sub))
        return out

    all_labels  = get_labels(train_ds)
    counts      = np.bincount(all_labels, minlength=N_CLASSES).astype(float)
    cls_w       = 1.0 / np.where(counts == 0, 1.0, counts)
    sample_w    = torch.tensor([cls_w[l] for l in all_labels])
    sampler     = WeightedRandomSampler(sample_w, len(sample_w), replacement=True)

    class_w_tensor = torch.tensor(cls_w / cls_w.sum() * N_CLASSES,
                                  dtype=torch.float, device=device)
    criterion   = nn.CrossEntropyLoss(weight=class_w_tensor)

    pin = device.type == "cuda"
    train_dl = DataLoader(train_ds, batch_size=32, sampler=sampler, num_workers=0, pin_memory=pin)
    val_dl   = DataLoader(val_ds,   batch_size=32, shuffle=False,   num_workers=0, pin_memory=pin)

    model     = build_model().to(device)
    optimiser = torch.optim.AdamW(model.parameters(), lr=lr, weight_decay=1e-4)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimiser, T_max=epochs)
    scaler    = torch.amp.GradScaler(device.type) if device.type == "cuda" else None

    best_acc, best_state = 0.0, None

    for epoch in range(1, epochs + 1):
        model.train()
        for imgs, kls in tqdm(train_dl, desc=f"  [{label}] Epoch {epoch}/{epochs}",
                               leave=False):
            imgs, kls = imgs.to(device), kls.to(device)
            optimiser.zero_grad()
            with torch.amp.autocast(device.type, enabled=scaler is not None):
                loss = criterion(model(imgs), kls)
            if scaler:
                scaler.scale(loss).backward(); scaler.step(optimiser); scaler.update()
            else:
                loss.backward(); optimiser.step()
        scheduler.step()

        model.eval()
        correct = total = 0
        with torch.no_grad():
            for imgs, kls in val_dl:
                preds  = model(imgs.to(device)).argmax(1)
                correct += (preds.cpu() == kls).sum().item()
                total   += kls.size(0)
        val_acc = correct / total
        if val_acc > best_acc:
            best_acc   = val_acc
            best_state = {k: v.clone() for k, v in model.state_dict().items()}
        print(f"  [{label}] Epoch {epoch:3d}  val_acc={val_acc:.4f}  best={best_acc:.4f}")

    model.load_state_dict(best_state)
    return model


@torch.no_grad()
def test_model(model, test_ds, device):
    loader = DataLoader(test_ds, batch_size=32, shuffle=False, num_workers=0)
    model.eval()
    all_probs, all_labels = [], []
    for imgs, kls in loader:
        probs = F.softmax(model(imgs.to(device)), dim=1)
        all_probs.append(probs.cpu())
        all_labels.append(kls)
    probs  = torch.cat(all_probs).numpy()
    labels = torch.cat(all_labels).numpy()
    return probs, labels


# ── Comparison plots ──────────────────────────────────────────────────────────
def plot_confusion_pair(y_true, y_base, y_aug, path: Path):
    fig, axes = plt.subplots(1, 2, figsize=(14, 6))
    for ax, preds, title in zip(axes, [y_base, y_aug],
                                ["Baseline (real only)", "Augmented (real + synthetic)"]):
        ConfusionMatrixDisplay.from_predictions(
            y_true, preds, display_labels=[f"KL={k}" for k in KL_CLASSES],
            ax=ax, cmap="Blues", colorbar=False
        )
        ax.set_title(title)
    fig.tight_layout()
    fig.savefig(path, dpi=120)
    plt.close(fig)
    print(f"Saved {path}")


def plot_f1_comparison(y_true, y_base, y_aug, path: Path):
    f1_base = f1_score(y_true, y_base, labels=KL_CLASSES, average=None, zero_division=0)
    f1_aug  = f1_score(y_true, y_aug,  labels=KL_CLASSES, average=None, zero_division=0)

    x     = np.arange(N_CLASSES)
    width = 0.35
    fig, ax = plt.subplots(figsize=(9, 5))
    ax.bar(x - width / 2, f1_base, width, label="Baseline",  color="steelblue")
    ax.bar(x + width / 2, f1_aug,  width, label="Augmented", color="darkorange")
    ax.set_xticks(x)
    ax.set_xticklabels([f"KL={k}" for k in KL_CLASSES])
    ax.set_ylabel("F1 Score")
    ax.set_ylim(0, 1.05)
    ax.set_title("Per-class F1: Baseline vs. Augmented (on real test set)")
    ax.legend()
    for i, (b, a) in enumerate(zip(f1_base, f1_aug)):
        delta = a - b
        color = "green" if delta > 0 else "red"
        ax.text(i + width / 2, a + 0.02, f"{delta:+.2f}", ha="center",
                fontsize=8, color=color, fontweight="bold")
    fig.tight_layout()
    fig.savefig(path, dpi=120)
    plt.close(fig)
    print(f"Saved {path}")
    return f1_base, f1_aug


def plot_roc_comparison(y_true, base_probs, aug_probs, path: Path):
    y_bin  = label_binarize(y_true, classes=KL_CLASSES)
    fig, axes = plt.subplots(1, 2, figsize=(14, 5))
    colors = ["steelblue", "darkorange", "seagreen", "tomato", "mediumpurple"]
    for ax, probs, title in zip(axes, [base_probs, aug_probs],
                                ["Baseline", "Augmented"]):
        for i, (kl, col) in enumerate(zip(KL_CLASSES, colors)):
            if y_bin[:, i].sum() == 0:
                continue
            fpr, tpr, _ = roc_curve(y_bin[:, i], probs[:, i])
            auc = roc_auc_score(y_bin[:, i], probs[:, i])
            ax.plot(fpr, tpr, color=col, label=f"KL={kl} AUC={auc:.3f}")
        ax.plot([0, 1], [0, 1], "k--", lw=0.8)
        ax.set_title(f"ROC — {title}")
        ax.set_xlabel("FPR"); ax.set_ylabel("TPR")
        ax.legend(fontsize=7)
    fig.tight_layout()
    fig.savefig(path, dpi=120)
    plt.close(fig)
    print(f"Saved {path}")


# ── Main ──────────────────────────────────────────────────────────────────────
def main():
    args = parse_args()
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Device: {device}  |  Generator: {args.generator}")

    train_tf = transforms.Compose([
        transforms.Resize(IMG_SIZE), transforms.CenterCrop(IMG_SIZE),
        transforms.RandomHorizontalFlip(),
        transforms.RandomAffine(degrees=10, translate=(0.05, 0.05)),
        transforms.ToTensor(), transforms.Normalize([0.5], [0.5]),
    ])
    eval_tf = transforms.Compose([
        transforms.Resize(IMG_SIZE), transforms.CenterCrop(IMG_SIZE),
        transforms.ToTensor(), transforms.Normalize([0.5], [0.5]),
    ])

    print("\nBuilding dataset index …")
    index = build_index(args.joint)
    train_idx, val_idx, test_idx = patient_split(index)

    from collections import Counter
    print("Train KL dist:", dict(sorted(Counter(k for _, k in train_idx).items())))
    print("Test  KL dist:", dict(sorted(Counter(k for _, k in test_idx).items())))

    train_real = RealDataset(train_idx, train_tf)
    val_ds     = RealDataset(val_idx,   eval_tf)
    test_ds    = RealDataset(test_idx,  eval_tf)

    # ── Baseline ──────────────────────────────────────────────────────────────
    baseline_ckpt = OUT_DIR / "baseline_model.pt"
    baseline_model = build_model().to(device)
    if baseline_ckpt.exists():
        print(f"\n=== Loading existing BASELINE model from {baseline_ckpt} ===")
        baseline_model.load_state_dict(torch.load(baseline_ckpt, map_location=device))
    else:
        print("\n=== Training BASELINE model (real images only) ===")
        baseline_model = train_model(train_real, val_ds, device,
                                     epochs=args.epochs, label="Baseline")
        torch.save(baseline_model.state_dict(), baseline_ckpt)
        print(f"Baseline model saved → {baseline_ckpt}")

    base_probs, y_true = test_model(baseline_model, test_ds, device)
    base_preds = base_probs.argmax(axis=1)

    print("\nBaseline classification report:")
    print(classification_report(y_true, base_preds,
                                 target_names=[f"KL={k}" for k in KL_CLASSES],
                                 zero_division=0))

    # ── Generate synthetic images ─────────────────────────────────────────────
    print("\n=== Generating synthetic images ===")
    synthetic: list[tuple[torch.Tensor, int]] = []

    for target_kl in AUGMENT_GRADES:
        source_kl = target_kl - 1
        if args.generator == "cyclegan":
            synthetic += generate_cyclegan(source_kl, target_kl,
                                           N_SYNTHETIC_PER_GRADE, train_idx, device)
        else:  # diffusion
            synthetic += generate_diffusion(target_kl, N_SYNTHETIC_PER_GRADE, device)

    if not synthetic:
        print("No synthetic images generated — run the generator first. Exiting.")
        return

    synth_ds   = SyntheticDataset(synthetic, eval_tf)
    train_aug  = ConcatDataset([train_real, synth_ds])

    from collections import Counter
    synth_dist = Counter(kl for _, kl in synthetic)
    print(f"Synthetic images added: {synth_dist}")

    # ── Augmented model ───────────────────────────────────────────────────────
    aug_ckpt  = OUT_DIR / "augmented_model.pt"
    aug_model = build_model().to(device)
    if aug_ckpt.exists():
        print(f"\n=== Loading existing AUGMENTED model from {aug_ckpt} ===")
        aug_model.load_state_dict(torch.load(aug_ckpt, map_location=device))
    else:
        print("\n=== Training AUGMENTED model (real + synthetic) ===")
        aug_model = train_model(train_aug, val_ds, device,
                                epochs=args.epochs, label="Augmented")
        torch.save(aug_model.state_dict(), aug_ckpt)
        print(f"Augmented model saved → {aug_ckpt}")

    aug_probs, _ = test_model(aug_model, test_ds, device)
    aug_preds    = aug_probs.argmax(axis=1)

    print("\nAugmented classification report:")
    print(classification_report(y_true, aug_preds,
                                 target_names=[f"KL={k}" for k in KL_CLASSES],
                                 zero_division=0))

    # ── Comparison plots ──────────────────────────────────────────────────────
    print("\n=== Saving comparison plots ===")
    plot_confusion_pair(y_true, base_preds, aug_preds,
                        OUT_DIR / "confusion_matrix_comparison.png")
    f1_base, f1_aug = plot_f1_comparison(y_true, base_preds, aug_preds,
                                          OUT_DIR / "f1_comparison.png")
    plot_roc_comparison(y_true, base_probs, aug_probs,
                        OUT_DIR / "roc_comparison.png")

    # ── Summary table ─────────────────────────────────────────────────────────
    acc_base = (base_preds == y_true).mean()
    acc_aug  = (aug_preds  == y_true).mean()

    results = pd.DataFrame({
        "KL_grade":       [f"KL={k}" for k in KL_CLASSES] + ["Overall accuracy"],
        "F1_Baseline":    list(f1_base.round(4)) + [round(acc_base, 4)],
        "F1_Augmented":   list(f1_aug.round(4))  + [round(acc_aug,  4)],
        "Delta":          list((f1_aug - f1_base).round(4)) + [round(acc_aug - acc_base, 4)],
    })
    print("\n── Summary ──")
    print(results.to_string(index=False))

    csv_path = OUT_DIR / "augmentation_study_results.csv"
    results.to_csv(csv_path, index=False)
    print(f"\nResults saved to {csv_path}")

    print(f"Models saved to {OUT_DIR}/")


def parse_args():
    p = argparse.ArgumentParser()
    p.add_argument("--generator", choices=["cyclegan", "diffusion"], default="cyclegan",
                   help="Which generator to use for synthetic images")
    p.add_argument("--epochs",    type=int, default=20,
                   help="Training epochs for each classifier (default 20)")
    p.add_argument("--joint",     type=str, default=None,
                   choices=list(JOINT_MAP.keys()))
    return p.parse_args()


if __name__ == "__main__":
    main()
